services:
  - type: web
    name: lgn-admin
    env: node
    rootDir: admin
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: quintana.mqf@gmail.com
      - key: ADMIN_PASSWORD
        value: admin
      - key: ADMIN_NAME
        value: LGN
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM
        sync: false
